version: '3.10'
services:
  web:
    image: krishnarajt/pc-usage-analyzer:1
    command: 
      - /bin/sh
      - -c
      - |
        cd PCUsageAnalyzer &&
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ${USERPROFILE}\Documents:/root/documents
    ports:
      - 8000:8000